version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: principal
      POSTGRES_USER: mbrownc
      POSTGRES_PASSWORD: 080520
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: mbrownc
      POSTGRES_PASSWORD: 080520
      POSTGRES_DB: principal
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run watch
